name: test

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: npm install
        run: npm install
      - name: unit tests
        run: npm test
      - name: generate coverage report
        run: npm run test:cov
      - name: upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: npm install
        run: npm install
      - name: e2e tests
        run: npm run test:e2e
