name: test

on: [push]

jobs:
  unit:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: install node v13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: npm install
        run: npm install
      - name: unit tests
        run: npm test
  e2e:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: install node v13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: npm install
        run: npm install
      - name: e2e tests
        run: npm run test:e2e
